### ISSUE TITLE
Add Copy to Clipboard

### ISSUE THREAD

**Issue by Ibochkarev** [Mark-H/DocsApp#8]
## What needs to be improved?

Add copy function to clipboard for code sections.
For example: https://prismjs.com/plugins/copy-to-clipboard/

Add a button that copies the code block to the clipboard when clicked.

**Comment by JoshuaLuckers** [comment]
I think there is no need for an external dependency: https://hackernoon.com/copying-text-to-clipboard-with-javascript-df4d4988697f

**Comment by Ibochkarev** [comment]
@JoshuaLuckers I have already done - I added a plugin for prism.js =)
